export enum ConsentType {
  WHATSAPP_MARKETING = 'WHATSAPP_MARKETING',
  EMAIL_MARKETING = 'EMAIL_MARKETING',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  COOKIES = 'COOKIES'
} 