export enum QuoteType {
  MOVING_QUOTE = 'MOVING_QUOTE',
  PACK = 'PACK',
  SERVICE = 'SERVICE'
}

export enum QuoteStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT'
} 