export enum ConfigurationCategory {
  PRICING = 'PRICING',
  BUSINESS_RULES = 'BUSINESS_RULES',
  LIMITS = 'LIMITS',
  SERVICE_PARAMS = 'SERVICE_PARAMS',
}

export enum PricingConfigKey {
  // Pack pricing
  PACK_BASE_PRICE = 'PACK_BASE_PRICE',
  PACK_WORKER_PRICE = 'PACK_WORKER_PRICE',
  PACK_INCLUDED_DISTANCE = 'PACK_INCLUDED_DISTANCE',
  PACK_EXTRA_KM_PRICE = 'PACK_EXTRA_KM_PRICE',
  PACK_EXTRA_DAY_DISCOUNT_RATE = 'PACK_EXTRA_DAY_DISCOUNT_RATE',
  PACK_WORKER_DISCOUNT_RATE_1_DAY = 'PACK_WORKER_DISCOUNT_RATE_1_DAY',
  PACK_WORKER_DISCOUNT_RATE_MULTI_DAYS = 'PACK_WORKER_DISCOUNT_RATE_MULTI_DAYS',
  PACK_LIFT_PRICE = 'PACK_LIFT_PRICE',
  
  // Service pricing
  SERVICE_BASE_PRICE = 'SERVICE_BASE_PRICE',
  SERVICE_WORKER_PRICE = 'SERVICE_WORKER_PRICE',
  SERVICE_WORKER_PRICE_PER_HOUR = 'SERVICE_WORKER_PRICE_PER_HOUR',
  SERVICE_WORKER_DISCOUNT_RATE_SHORT = 'SERVICE_WORKER_DISCOUNT_RATE_SHORT',
  SERVICE_WORKER_DISCOUNT_RATE_LONG = 'SERVICE_WORKER_DISCOUNT_RATE_LONG',
  
  // Moving pricing
  MOVING_BASE_PRICE = 'MOVING_BASE_PRICE',
  MOVING_BASE_PRICE_PER_M3 = 'MOVING_BASE_PRICE_PER_M3',
  MOVING_DISTANCE_PRICE_PER_KM = 'MOVING_DISTANCE_PRICE_PER_KM',
  MOVING_WORKER_PRICE = 'MOVING_WORKER_PRICE',
  MOVING_TRUCK_PRICE = 'MOVING_TRUCK_PRICE',
  FUEL_CONSUMPTION_PER_100KM = 'FUEL_CONSUMPTION_PER_100KM',
  FUEL_PRICE_PER_LITER = 'FUEL_PRICE_PER_LITER',
  TOLL_COST_PER_KM = 'TOLL_COST_PER_KM',
  HIGHWAY_RATIO = 'HIGHWAY_RATIO',
}

export enum BusinessRulesConfigKey {
  // Pack rules
  PACK_EARLY_BOOKING_DAYS = 'PACK_EARLY_BOOKING_DAYS',
  PACK_EARLY_BOOKING_DISCOUNT = 'PACK_EARLY_BOOKING_DISCOUNT',
  PACK_WEEKEND_SURCHARGE = 'PACK_WEEKEND_SURCHARGE',
  PACK_URGENT_BOOKING_SURCHARGE = 'PACK_URGENT_BOOKING_SURCHARGE',
  
  // Service rules
  SERVICE_EARLY_BOOKING_DAYS = 'SERVICE_EARLY_BOOKING_DAYS',
  SERVICE_EARLY_BOOKING_DISCOUNT = 'SERVICE_EARLY_BOOKING_DISCOUNT',
  SERVICE_WEEKEND_SURCHARGE = 'SERVICE_WEEKEND_SURCHARGE',
  
  // Moving rules
  MOVING_EARLY_BOOKING_DAYS = 'MOVING_EARLY_BOOKING_DAYS',
  MOVING_EARLY_BOOKING_DISCOUNT = 'MOVING_EARLY_BOOKING_DISCOUNT',
  MOVING_WEEKEND_SURCHARGE = 'MOVING_WEEKEND_SURCHARGE',
}

export enum LimitsConfigKey {
  MIN_BOOKING_HOURS = 'MIN_BOOKING_HOURS',
  MAX_BOOKING_DAYS_AHEAD = 'MAX_BOOKING_DAYS_AHEAD',
  MIN_WORKERS = 'MIN_WORKERS',
  MAX_WORKERS = 'MAX_WORKERS',
}

export enum ServiceParamsConfigKey {
  AVAILABLE_PACK_TYPES = 'AVAILABLE_PACK_TYPES',
  AVAILABLE_SERVICE_TYPES = 'AVAILABLE_SERVICE_TYPES',
  AVAILABLE_MOVING_TYPES = 'AVAILABLE_MOVING_TYPES',
  DEFAULT_CURRENCY = 'DEFAULT_CURRENCY',
  WORKING_HOURS_START = 'WORKING_HOURS_START',
  WORKING_HOURS_END = 'WORKING_HOURS_END',
  WORKING_DAYS = 'WORKING_DAYS',
  DEFAULT_TRAVEL_SPEED = 'DEFAULT_TRAVEL_SPEED',
  WORKER_SETUP_TIME = 'WORKER_SETUP_TIME',
} 